<?xml version="1.0"?>
<robot name="robot_one" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- Body dimensions / wheel dimensions / material density / pi constant / Robot body & wheel mass-->

    <xacro:property name="base_x" value="1"/>
    <xacro:property name="base_y" value="0.6"/>
    <xacro:property name="base_z" value="0.2"/>

    <xacro:property name="wheel_radius" value="0.15"/>
    <xacro:property name="wheel_length" value="0.1"/>
    <xacro:property name="wheel_location" value="-0.1"/>

    <xacro:property name="base_density" value="2710.0"/>
    <xacro:property name="wheel_density" value="2710.0"/> <!-- in kg/m3-->

    <!-- <xacro:property name="pi" value="3.14159265"/> -->

    <xacro:property name="body_mass" value="${base_density * base_x * base_y * base_z}"/>
    <xacro:property name="wheel_mass" value="${wheel_density * pi * wheel_radius * wheel_radius * wheel_length}"/>

    <!-- MOI -->
    <xacro:property name="wheel_Iz" value="${0.5 * wheel_mass * wheel_radius * wheel_radius}"/>
    <xacro:property name="wheel_I" value="${(1 / 12) * wheel_mass * (3 * wheel_radius * wheel_radius + wheel_length * wheel_length)}"/>


    <xacro:macro name="inertial_wheel">
        <inertial>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <mass value="${wheel_mass}"/>
            <inertia ixx="${wheel_I}" ixy="0.0" ixz="0.0" iyy="${wheel_I}" iyz="0.0" izz="${wheel_Iz}"/>
        </inertial>
    </xacro:macro>

    <!-- motion control drive -->
    <xacro:include filename="$(find robot_one)/model/robot.gazebo"/>
    <!-- <xacro:include filename="robot.gazebo"/> -->

    <material name="yellow">
        <color rgba="1 1 0 1"/>
    </material>
    <material name="red"> 
        <color rgba="1 0 0 1"/>
    </material>

    <!-- Links and Joints -->
    <!-- <link name="dummy"> </link>
    <joint name="world_joint" type="fixed">
        <parent link="dummy"/>
        <child link="body_link"/>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
    </joint> -->

    <link name="body_link">
        <visual>
            <origin xyz="0 0 0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size=" ${base_x} ${base_y} ${base_z}"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${base_x} ${base_y} ${base_z}"/>
            </geometry>
            <material>
                <color rgba="0 1 0 1"/>
            </material>
        </collision>
        <inertial>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <mass value="${body_mass}"/>
            <inertia 
            ixx="${(1 / 12) * body_mass * (base_y * base_y + base_z * base_z) }" 
            ixy="0" 
            ixz="0" 
            iyy="${(1 / 12) * body_mass * (base_x * base_x + base_z * base_z) }" 
            iyz="0.0" 
            izz="${(1 / 12) * body_mass * (base_y * base_y + base_x * base_x) }" />
        </inertial>    
    </link>



 <joint name="wheel_1_joint" type="continuous">
        <origin xyz="${-base_x / 2 + 1.2 * wheel_radius} ${-base_y / 2 - wheel_length / 2} ${wheel_location}" rpy="0.0 0.0 0.0"/>
        <parent link="body_link"/>
        <child link="wheel_1_link"/>
        <axis xyz="0.0 1.0 0.0"/>
        <limit effort="1000.0" velocity="1000.0"/>
        <dynamics damping="1.0" friction="1.0"/>
    </joint>

    <link name="wheel_1_link">
        <visual>
            <origin rpy="${pi/2} 0.0 0.0" xyz="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_radius}"/>
            </geometry>
            <material name="yellow"/>
        </visual>
        <collision>
            <origin rpy="${pi/2} 0.0 0.0" xyz="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_wheel/>
    </link>

    <!-- wheel 2  -->
    <joint name="wheel_2_joint" type="continuous">
        <origin xyz="${-base_x / 2 + 1.2 * wheel_radius} ${base_y / 2 + wheel_length / 2} ${wheel_location}" rpy="0.0 0.0 0.0"/>
        <parent link="body_link"/>
        <child link="wheel_2_link"/>
        <axis xyz="0.0 1.0 0.0"/>
        <limit effort="1000.0" velocity="1000.0"/>
        <dynamics damping="1.0" friction="1.0"/>
    </joint>

    <link name="wheel_2_link">
        <visual>
            <origin rpy="${pi/2} 0.0 0.0" xyz="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_radius}"/>
            </geometry>
            <material name="yellow"/>
        </visual>
        <collision>
            <origin rpy="${pi/2} 0.0 0.0" xyz="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_wheel/>
    </link>

    <!-- wheel 3  -->
    <joint name="wheel_3_joint" type="continuous">
        <origin xyz="${base_x / 2 - 1.2 * wheel_radius} ${-base_y / 2 - wheel_length / 2} ${wheel_location}" rpy="0.0 0.0 0.0"/>
        <parent link="body_link"/>
        <child link="wheel_3_link"/>
        <axis xyz="0.0 1.0 0.0"/>
        <limit effort="1000.0" velocity="1000.0"/>
        <dynamics damping="1.0" friction="1.0"/>
    </joint>

    <link name="wheel_3_link">
        <visual>
            <origin rpy="${pi/2} 0.0 0.0" xyz="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_radius}"/>
            </geometry>
            <material name="yellow"/>
        </visual>
        <collision>
            <origin rpy="${pi/2} 0.0 0.0" xyz="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_wheel/>
    </link>

    <!-- wheel 4  -->
    <joint name="wheel_4_joint" type="continuous">
        <origin xyz="${base_x / 2 - 1.2 * wheel_radius} ${base_y / 2 + wheel_length / 2} ${wheel_location}" rpy="0.0 0.0 0.0"/>
        <parent link="body_link"/>
        <child link="wheel_4_link"/>
        <axis xyz="0.0 1.0 0.0"/>
        <limit effort="1000.0" velocity="1000.0"/>
        <dynamics damping="1.0" friction="1.0"/>
    </joint>

    <link name="wheel_4_link">
        <visual>
            <origin rpy="${pi/2} 0.0 0.0" xyz="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_radius}"/>
            </geometry>
            <material name="yellow"/>
        </visual>
        <collision>
            <origin rpy="${pi/2} 0.0 0.0" xyz="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_wheel/>
    </link>
   
   
 
</robot>










